title: Christian Torchia

markdown: kramdown
highlighter: none

kramdown:
  input: GFM
  hard_wrap: true
  smart_quotes: ["apos", "apos", "quot", "quot"]

collections:
  writeups:
    output: true

exclude:
  - PUBBLICARE.md
  - setup-sito.sh
  - FETCH_HEAD
  - Gemfile
  - Gemfile.lock
  - vendor
